// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayShop.DataAccess.Models;

public partial class Photo
{
    [Key]
    public long PhotoId { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [Required]
    [StringLength(50)]
    public string Filename { get; set; }

    [Required]
    public byte[] PhotoBytes { get; set; }

    [InverseProperty("ThumbnailPhoto")]
    public virtual ICollection<Product> Product { get; set; } = new List<Product>();
}