// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace FairPlayShop.DataAccess.Models;

public partial class StoreCustomerAddress
{
    [Key]
    public long StoreCustomerAddressId { get; set; }

    public int CountryId { get; set; }

    [Required]
    [StringLength(50)]
    public string Firstname { get; set; }

    [Required]
    [StringLength(50)]
    public string Lastname { get; set; }

    [StringLength(50)]
    public string Company { get; set; }

    [Required]
    [StringLength(50)]
    public string AddressLine1 { get; set; }

    [Required]
    [StringLength(50)]
    public string AddressLine2 { get; set; }

    public int CityId { get; set; }

    [Required]
    [StringLength(10)]
    public string PostalCode { get; set; }

    [Required]
    [StringLength(50)]
    public string PhoneNumber { get; set; }

    public long StoreCustomerId { get; set; }

    [ForeignKey("CityId")]
    [InverseProperty("StoreCustomerAddress")]
    public virtual City City { get; set; }

    [ForeignKey("StoreCustomerId")]
    [InverseProperty("StoreCustomerAddress")]
    public virtual StoreCustomer StoreCustomer { get; set; }
}