//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairPlayShop.AutomatedTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FairPlayShop.AutomatedTests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Post-Deployment Script Template							
        ///--------------------------------------------------------------------------------------
        /// This file contains SQL statements that will be appended to the build script.		
        /// Use SQLCMD syntax to include a file in the post-deployment script.			
        /// Example:      :r .\myfile.sql								
        /// Use SQLCMD syntax to reference a variable in the post-deployment script.		
        /// Example:      :setvar TableName MyTable							
        ///               SELECT * FROM [$(TableName)]					
        ///----------- [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SeedData {
            get {
                return ResourceManager.GetString("SeedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] TestProduct {
            get {
                object obj = ResourceManager.GetObject("TestProduct", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResourceId,Type,Key,Value,CultureId
        ///5791,FairPlayShop.Models.Store.CreateStoreModelLocalizer,Name_RequiredText,{0} is required,1
        ///5792,FairPlayShop.Models.Store.CreateStoreModelLocalizer,NameStringLengthText,{0} cannot have more than {1} characters,1
        ///5793,FairPlayShop.Models.StoreCustomer.CreateStoreCustomerModelLocalizer,StoreId_RequiredText,{0} is required,1
        ///5794,FairPlayShop.Models.StoreCustomer.CreateStoreCustomerModelLocalizer,Name_RequiredText,{0} is required,1
        ///5795,FairPlayShop.Models.StoreCustom [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Translations {
            get {
                return ResourceManager.GetString("Translations", resourceCulture);
            }
        }
    }
}
