using FairPlayShop.Common.CustomAttributes;
using Microsoft.Extensions.Localization;

namespace FairPlayShop.CustomLocalization
{
    public class GlobalKeysLocalizer
    {
        protected GlobalKeysLocalizer() { }
        public static IStringLocalizer<GlobalKeysLocalizer>? Localizer { get; set; }
        public static string SaveText => Localizer![SaveTextKey];
        public static string PaginatorSummaryText => Localizer![PaginatorSummaryTextKey];
        public static string ContentGeneratedByAzureOpenAIText => Localizer![ContentGeneratedByAzureOpenAITextKey];
        [ResourceKey(defaultValue: "Save")]
        public const string SaveTextKey = "SaveText";
        [ResourceKey("Page {0} of {1}. Total Items: {2}")]
        public const string PaginatorSummaryTextKey = "PaginatorSummaryText";
        [ResourceKey(defaultValue:"Disclaimer: The following content has been generated by Azure Open AI." +
            "AI generated content may not be accurate.")]
        public const string ContentGeneratedByAzureOpenAITextKey = "ContentGeneratedByAzureOpenAIText";
    }
}
